FROM node:18.14.0 as builder

WORKDIR /work

ENV STAGE=production

COPY . .

RUN yarn install --frozen-lockfile && yarn build

FROM node:18-alpine as runner

ENV STAGE=production

WORKDIR /app

COPY --from=builder /work/build/ /work/package.json /work/yarn.lock ./

RUN yarn install --production --frozen-lockfile 

CMD ["node", "bundle.js"]